name: Publish Docker image
on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
name: Publish Docker image
on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main    
    paths-ignore:
      - '**/README.md' 
      - '**/.gitignore' 
      - '**/demo.gif'
      - '**/docker-compose.yml'
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Server
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          file: ./server/Dockerfile
          push: true
          tags: |
            derrick56007/iss_server:${{ github.sha }}          
            derrick56007/iss_server:latest
            
      - name: Build and Push UI
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          context: ./ui/
          file: ./ui/Dockerfile
          push: true
          tags: |
            derrick56007/iss_ui:${{ github.sha }}          
            derrick56007/iss_ui:latest            
            
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
