name: Publish Docker image
on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./.devcontainer/
          file: ./.devcontainer/Dockerfile
          push: true
          tags: |
            derrick56007/rust_devcontainer:${{ github.sha }}          
            derrick56007/rust_devcontainer:latest       
            
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
